# -*- coding: utf-8 -*-
"""atsronomyChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XP-XOQInREN--jNPUN_Ez59DhQFv1-N
"""

import os
import requests
from datetime import datetime, timedelta
import json

# API Keys
NASA_API_KEY = os.getenv('NASA_API_KEY', 'DEMO_KEY')
NASA_BASE_URL = "https://api.nasa.gov"

def get_nasa_insight_data():
    """Get Mars InSight weather data"""
    url = f"{NASA_BASE_URL}/insight_weather/?api_key={NASA_API_KEY}&feedtype=json&ver=1.0"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        return {"success": True, "data": data}
    except Exception as e:
        return {"success": False, "error": str(e)}

def get_nasa_donki_data(event_type="all", days=30):
    """
    Get space weather events from DONKI (Space Weather Database Of Notifications, Knowledge, Information)
    Event types: CME, GST, IPS, FLR, SEP, MPC, RBE, report, ALL
    """
    end_date = datetime.now()
    start_date = end_date - timedelta(days=days)

    url = f"{NASA_BASE_URL}/DONKI/notifications"
    params = {
        "startDate": start_date.strftime("%Y-%m-%d"),
        "endDate": end_date.strftime("%Y-%m-%d"),
        "type": event_type,
        "api_key": NASA_API_KEY
    }

    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        return {"success": True, "data": data, "count": len(data)}
    except Exception as e:
        return {"success": False, "error": str(e)}

def get_nasa_eonet_events(category=None, days=30):
    """
    Get natural events from EONET (Earth Observatory Natural Event Tracker)
    Categories: wildfires, volcanoes, severe storms, floods, droughts, etc.
    """
    url = "https://eonet.gsfc.nasa.gov/api/v3/events"
    params = {"days": days, "status": "open"}

    if category:
        params["category"] = category

    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        return {"success": True, "data": data, "count": len(data.get("events", []))}
    except Exception as e:
        return {"success": False, "error": str(e)}

def get_exoplanet_data(query_type="count"):
    """
    Get exoplanet data from NASA Exoplanet Archive
    Query types: count, recent, or specific searches
    """
    base_url = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync"

    if query_type == "count":
        query = "select count(*) as total from ps where default_flag=1"
    elif query_type == "recent":
        query = "select pl_name,hostname,disc_year,pl_rade,pl_masse from ps where default_flag=1 order by disc_year desc"
    else:
        query = query_type

    params = {
        "query": query,
        "format": "json"
    }

    try:
        response = requests.get(base_url, params=params, timeout=15)
        response.raise_for_status()
        data = response.json()
        return {"success": True, "data": data}
    except Exception as e:
        return {"success": False, "error": str(e)}

def get_nasa_apod():
    """Get NASA's Astronomy Picture of the Day"""
    url = f"{NASA_BASE_URL}/planetary/apod?api_key={NASA_API_KEY}"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        return {"success": True, "data": data}
    except Exception as e:
        return {"success": False, "error": str(e)}

def format_insight_response(data):
    """Format Mars InSight data into readable response"""
    if not data.get("success"):
        return "Sorry, I couldn't retrieve Mars weather data at the moment."

    try:
        sols = data["data"].get("sol_keys", [])
        if not sols:
            return "Mars InSight data is currently unavailable. The InSight mission ended in December 2022 after losing power."

        latest_sol = sols[-1]
        sol_data = data["data"].get(latest_sol, {})

        response = f"**Mars Weather (Sol {latest_sol}):**\n"
        if "AT" in sol_data:
            temp_data = sol_data["AT"]
            response += f"Temperature: {temp_data.get('av', 'N/A')}°C (avg), "
            response += f"Min: {temp_data.get('mn', 'N/A')}°C, Max: {temp_data.get('mx', 'N/A')}°C\n"

        if "HWS" in sol_data:
            wind_data = sol_data["HWS"]
            response += f"Wind Speed: {wind_data.get('av', 'N/A')} m/s (avg)\n"

        if "PRE" in sol_data:
            pressure_data = sol_data["PRE"]
            response += f"Pressure: {pressure_data.get('av', 'N/A')} Pa (avg)\n"

        return response
    except:
        return "Mars InSight mission ended in December 2022. Historical data may be available through NASA archives."

def format_donki_response(data):
    """Format DONKI space weather data into readable response"""
    if not data.get("success"):
        return "Sorry, I couldn't retrieve space weather data at the moment."

    events = data["data"]
    count = data["count"]

    if count == 0:
        return "**Space Weather Update:** No significant space weather events in the last 30 days. The Sun has been relatively quiet!"

    response = f"**Space Weather Events (Last 30 days): {count} events found**\n\n"

    for i, event in enumerate(events[:5]):  # Show first 5 events
        message_type = event.get("messageType", "Unknown")
        message_body = event.get("messageBody", "No details available")
        issue_time = event.get("messageIssueTime", "Unknown time")

        response += f"{i+1}. [{message_type}] - {issue_time}\n"
        response += f"   {message_body[:200]}...\n\n"

    if count > 5:
        response += f"... and {count - 5} more events.\n"

    return response

def format_eonet_response(data):
    """Format EONET Earth events data into readable response"""
    if not data.get("success"):
        return "Sorry, I couldn't retrieve Earth observation data at the moment."

    events = data["data"].get("events", [])
    count = data["count"]

    if count == 0:
        return "**Earth Events:** No major natural events currently being tracked by NASA satellites."

    response = f"**Active Natural Events (NASA EONET): {count} events**\n\n"

    event_types = {}
    for event in events:
        categories = event.get("categories", [])
        for cat in categories:
            cat_title = cat.get("title", "Unknown")
            event_types[cat_title] = event_types.get(cat_title, 0) + 1

    response += "Event breakdown:\n"
    for event_type, num in sorted(event_types.items(), key=lambda x: x[1], reverse=True):
        response += f"  • {event_type}: {num}\n"

    response += "\nRecent events:\n"
    for i, event in enumerate(events[:5]):
        title = event.get("title", "Unknown")
        categories = ", ".join([c.get("title", "") for c in event.get("categories", [])])
        response += f"{i+1}. {title} ({categories})\n"

    return response

def format_exoplanet_response(count_data, recent_data):
    """Format exoplanet data into readable response"""
    response = "**Exoplanet Discovery Status:**\n\n"

    if count_data.get("success"):
        total = count_data["data"][0].get("total", "Unknown")
        response += f"Total confirmed exoplanets: **{total}**\n\n"

    if recent_data.get("success"):
        planets = recent_data["data"][:10]
        response += "Recent discoveries:\n"
        for i, planet in enumerate(planets[:5]):
            name = planet.get("pl_name", "Unknown")
            host = planet.get("hostname", "Unknown")
            year = planet.get("disc_year", "Unknown")
            radius = planet.get("pl_rade", "Unknown")

            response += f"{i+1}. {name} (orbits {host}, discovered {year})\n"
            if radius and radius != "Unknown":
                response += f"   Radius: {radius} Earth radii\n"

    response += "\nThese planets orbit stars outside our solar system and represent humanity's search for worlds beyond our own!"

    return response

def format_apod_response(data):
    """Format Astronomy Picture of the Day response"""
    if not data.get("success"):
        return "Sorry, I couldn't retrieve today's Astronomy Picture of the Day."

    apod = data["data"]
    title = apod.get("title", "No title")
    explanation = apod.get("explanation", "No explanation available")
    url = apod.get("url", "")
    media_type = apod.get("media_type", "image")
    date = apod.get("date", "today")

    response = f"**🌌 Astronomy Picture of the Day ({date}):**\n\n"
    response += f"**{title}**\n\n"
    response += f"{explanation}\n\n"
    response += f"Media type: {media_type}\n"
    response += f"View it here: {url}\n"

    return response

def get_astronomy_response(user_input):
    """
    Answer astronomy questions using NASA APIs and built-in knowledge
    """
    user_lower = user_input.lower()
    response = ""

    # Check for Mars/InSight queries
    if any(word in user_lower for word in ["mars", "insight", "martian", "red planet", "weather on mars"]):
        print("🛰️  Fetching Mars InSight data...")
        insight_data = get_nasa_insight_data()
        response += format_insight_response(insight_data) + "\n\n"

        if "mars" in user_lower and not any(word in user_lower for word in ["weather", "temperature", "insight"]):
            response += "Mars is the fourth planet from the Sun, known for its reddish appearance due to iron oxide on its surface. "
            response += "It has two small moons (Phobos and Deimos), a thin atmosphere mostly of CO2, and evidence of ancient water flows. "
            response += "NASA's rovers and landers continue to explore Mars for signs of past life.\n"

    # Check for space weather queries
    elif any(word in user_lower for word in ["solar", "sun", "flare", "cme", "space weather", "aurora", "geomagnetic", "coronal mass"]):
        print("🛰️  Fetching DONKI space weather data...")
        donki_data = get_nasa_donki_data()
        response += format_donki_response(donki_data) + "\n\n"
        response += "Space weather refers to conditions on the Sun and in space that can affect technology and astronauts. "
        response += "Solar flares and coronal mass ejections (CMEs) can impact satellites, communications, and power grids on Earth.\n"

    # Check for Earth events queries
    elif any(word in user_lower for word in ["wildfire", "volcano", "storm", "flood", "drought", "earth event", "eonet", "natural disaster"]):
        print("🛰️  Fetching EONET Earth observation data...")
        eonet_data = get_nasa_eonet_events()
        response += format_eonet_response(eonet_data) + "\n\n"
        response += "NASA satellites continuously monitor Earth for natural events like wildfires, volcanic eruptions, and severe storms, "
        response += "helping scientists track and respond to environmental changes.\n"

    # Check for exoplanet queries
    elif any(word in user_lower for word in ["exoplanet", "extrasolar", "planet outside", "discovered planet", "kepler", "tess"]):
        print("🛰️  Fetching Exoplanet Archive data...")
        count_data = get_exoplanet_data("count")
        recent_data = get_exoplanet_data("recent")
        response += format_exoplanet_response(count_data, recent_data) + "\n"

    # Check for APOD queries
    elif any(word in user_lower for word in ["picture", "photo", "image", "apod", "astronomy picture"]):
        print("🛰️  Fetching Astronomy Picture of the Day...")
        apod_data = get_nasa_apod()
        response += format_apod_response(apod_data) + "\n"

    # General astronomy knowledge base
    elif "planet" in user_lower:
        response = "There are 8 planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.\n\n"
        response += "• **Terrestrial planets** (rocky): Mercury, Venus, Earth, Mars\n"
        response += "• **Gas giants**: Jupiter, Saturn\n"
        response += "• **Ice giants**: Uranus, Neptune\n\n"
        response += "Each planet has unique characteristics. Which one would you like to know more about?"

    elif "star" in user_lower:
        response = "Stars are massive spheres of plasma that generate energy through nuclear fusion in their cores. "
        response += "Our Sun is a medium-sized star about 4.6 billion years old.\n\n"
        response += "Stars are classified by temperature and brightness:\n"
        response += "• O and B stars: Hot, blue stars\n"
        response += "• A and F stars: White stars\n"
        response += "• G stars: Yellow stars (like our Sun)\n"
        response += "• K and M stars: Orange and red stars\n\n"
        response += "The closest star to Earth (besides the Sun) is Proxima Centauri, about 4.24 light-years away."

    elif "black hole" in user_lower:
        response = "Black holes are regions of spacetime where gravity is so strong that nothing, not even light, can escape. "
        response += "They form when massive stars collapse at the end of their lives.\n\n"
        response += "**Types of black holes:**\n"
        response += "• Stellar black holes: 3-100 solar masses\n"
        response += "• Supermassive black holes: millions to billions of solar masses (found in galaxy centers)\n"
        response += "• Intermediate black holes: 100-100,000 solar masses\n\n"
        response += "The closest known black hole is Gaia BH1, approximately 1,560 light-years away, discovered in 2022."

    elif "moon" in user_lower:
        response = "Earth's Moon is our planet's only natural satellite, orbiting at an average distance of 238,855 miles (384,400 km). "
        response += "It's about 1/4 the diameter of Earth and influences our tides through gravitational pull.\n\n"
        response += "The Moon formed about 4.5 billion years ago, likely from debris after a Mars-sized object collided with early Earth. "
        response += "It has no atmosphere, and temperatures range from -173°C to 127°C."

    elif "galaxy" in user_lower or "milky way" in user_lower:
        response = "Our galaxy, the Milky Way, is a barred spiral galaxy containing 100-400 billion stars. "
        response += "It's about 100,000 light-years in diameter, and our Sun is located about 26,000 light-years from the galactic center.\n\n"
        response += "The closest galaxy to the Milky Way is the Canis Major Dwarf Galaxy, about 25,000 light-years away. "
        response += "The Andromeda Galaxy (M31) is the nearest large spiral galaxy, about 2.5 million light-years away, "
        response += "and it's on a collision course with the Milky Way (they'll merge in about 4.5 billion years)."

    elif "asteroid" in user_lower:
        response = "Asteroids are rocky, metallic objects that orbit the Sun but are too small to be considered planets. "
        response += "Most asteroids are found in the asteroid belt between Mars and Jupiter.\n\n"
        response += "**Notable asteroids:**\n"
        response += "• Ceres: Largest asteroid, now classified as a dwarf planet\n"
        response += "• Vesta: Second-largest asteroid\n"
        response += "• Near-Earth asteroids: Those that pass close to Earth\n\n"
        response += "NASA's DART mission successfully demonstrated asteroid deflection technology in 2022."

    elif "comet" in user_lower:
        response = "Comets are icy bodies that release gas and dust as they approach the Sun, creating spectacular tails. "
        response += "They're often called 'dirty snowballs' made of ice, dust, rock, and frozen gases.\n\n"
        response += "Famous comets include:\n"
        response += "• Halley's Comet: Returns every 76 years\n"
        response += "• Hale-Bopp: Visible to the naked eye in 1997\n"
        response += "• NEOWISE: Discovered in 2020\n\n"
        response += "Most comets originate from the Kuiper Belt or Oort Cloud at the edge of our solar system."

    elif "nebula" in user_lower:
        response = "Nebulae are vast clouds of gas and dust in space, often serving as stellar nurseries where new stars are born.\n\n"
        response += "**Types of nebulae:**\n"
        response += "• Emission nebulae: Glow from ionized gas (e.g., Orion Nebula)\n"
        response += "• Reflection nebulae: Reflect light from nearby stars\n"
        response += "• Dark nebulae: Dense clouds that block background light\n"
        response += "• Planetary nebulae: Shells of gas from dying stars (e.g., Ring Nebula)\n\n"
        response += "The Eagle Nebula (M16) contains the famous 'Pillars of Creation' photographed by Hubble."

    elif any(name in user_lower for name in ["mercury", "venus", "jupiter", "saturn", "uranus", "neptune"]):
        if "mercury" in user_lower:
            response = "Mercury is the smallest planet and closest to the Sun. It has extreme temperature variations "
            response += "(430°C day, -180°C night) and no atmosphere. Its year is 88 Earth days, but a day lasts 59 Earth days!"
        elif "venus" in user_lower:
            response = "Venus is the hottest planet due to its thick CO2 atmosphere creating a runaway greenhouse effect (465°C surface). "
            response += "It rotates backwards compared to most planets and has crushing atmospheric pressure 90 times Earth's."
        elif "jupiter" in user_lower:
            response = "Jupiter is the largest planet, with a mass 2.5 times all other planets combined. Its Great Red Spot is a "
            response += "storm larger than Earth that's raged for centuries. Jupiter has 95 known moons, including Ganymede (the largest in the solar system)."
        elif "saturn" in user_lower:
            response = "Saturn is famous for its spectacular ring system made of ice and rock particles. It's the least dense planet "
            response += "(it would float in water!). Saturn has 146 known moons, with Titan being larger than Mercury."
        elif "uranus" in user_lower:
            response = "Uranus is an ice giant with an extreme axial tilt of 98°, essentially rotating on its side. This causes "
            response += "extreme seasonal variations. It has a pale blue-green color from methane in its atmosphere and 27 known moons."
        elif "neptune" in user_lower:
            response = "Neptune is the most distant planet, with winds reaching 2,100 km/h - the fastest in the solar system. "
            response += "It's similar to Uranus in composition. Neptune has 16 known moons, with Triton being geologically active."

    else:
        response = "I'm an astronomy assistant with access to multiple NASA APIs! I can tell you about:\n\n"
        response += "🔴 **Mars & InSight** - Current weather data from Mars\n"
        response += "☀️ **Space Weather (DONKI)** - Solar flares, CMEs, and geomagnetic storms\n"
        response += "🌍 **Earth Events (EONET)** - Wildfires, volcanoes, storms tracked by NASA\n"
        response += "🪐 **Exoplanets** - Planets orbiting other stars\n"
        response += "📸 **Astronomy Picture of the Day** - Today's cosmic image\n\n"
        response += "I also know about: planets, stars, moons, galaxies, black holes, asteroids, comets, nebulae, and more!\n\n"
        response += "a would you like to explore?"

    return response

def main():
    print("=" * 70)
    print("🌟 NASA-Powered Astronomy Bot 🌟")
    print("=" * 70)
    print("Hi! I'm your astronomy assistant with access to NASA's APIs.")
    print("\nI can provide real-time data from:")
    print("  • Mars InSight weather")
    print("  • DONKI space weather events")
    print("  • EONET Earth observation")
    print("  • NASA Exoplanet Archive")
    print("  • Astronomy Picture of the Day")
    print("\nAsk me anything about space! Type 'exit' to end.")
    print("=" * 70)
    print()

    while True:
        user_input = input("You: ").strip()

        if not user_input:
            continue

        if user_input.lower() == 'exit':
            print("\nAstronomy Bot: Goodbye! Keep exploring the cosmos! 🚀")
            break

        print()
        response = get_astronomy_response(user_input)
        print(f"Astronomy Bot:\n{response}")
        print()

if __name__ == "__main__":
    main()